### ISSUE TITLE
How to get alert on filesystem storage disks-wise ?

### ISSUE THREAD

**Issue by amolkekan** [YelpArchive/elastalert#2095]
@Qmando 
I am using "system.filesystem.used.pct" key to calculate and raise an alert. But the issue is that the server is having extra disk attached and using the below rule it gives alert depending on average of both 2 disk space utilized. My root volume was at 85% and other was at 20%, so the average was below 80%. Hence it did not raise an alert.

I want to alert when any of the disks utilzation goes above 80%
Please help. 

Here is my rule

```
name: Filesystem Alert
type: metric_aggregation

index: metricbeat-*


metric_agg_key: system.filesystem.used.pct
metric_agg_type: avg

query_key: beat.hostname

doc_type: doc

bucket_interval:
  minutes: 15

sync_bucket_interval: true

max_threshold: 0.8

filter:
- term:
    metricset.name: filesystem

alert:
- "email"

alert_subject: "MPL Alarm: FS Storage > 80% on host {0} ({1})"
alert_subject_args:
- "beat.hostname"
- "system.filesystem.used.pct_avg"

alert_text: |
        -------------  ALERT -------------
        TITLE: FS Storage > 80% for last 15 mins
        ACTUAL VALUE: {0}
        HOST: {1}
        TIMESTAMP: {2}
        KIBANA: {3}

alert_text_args: ["system.filesystem.used.pct", "beat.hostname", "@timestamp", "kibana_link"]

```
